from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='WipRefProductRule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('sort_no', models.IntegerField(default=0)),('lot_char_1', models.CharField(blank=True, default='', max_length=20)),('lot_char_2', models.CharField(blank=True, default='', max_length=20)),('lot_char_3', models.CharField(blank=True, default='', max_length=20)),('lot_char_4', models.CharField(blank=True, default='', max_length=20)),('lot_char_5', models.CharField(blank=True, default='', max_length=20)),('processed', models.CharField(blank=True, default='', max_length=50)),('product_name', models.CharField(max_length=100)),('is_active', models.BooleanField(default=True)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True))], options={'db_table':'wip_ref_product_rule'}),
        migrations.CreateModel(name='WipRefModuleRule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('sort_no', models.IntegerField(default=0)),('product_name', models.CharField(max_length=100)),('start_layer', models.CharField(blank=True, default='', max_length=50)),('end_layer', models.CharField(blank=True, default='', max_length=50)),('start_stepseq', models.CharField(blank=True, default='', max_length=50)),('end_stepseq', models.CharField(blank=True, default='', max_length=50)),('module_name', models.CharField(max_length=100)),('is_active', models.BooleanField(default=True)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True))], options={'db_table':'wip_ref_module_rule'}),
        migrations.CreateModel(name='WipRefExclusionTypeRule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('sort_no', models.IntegerField(default=0)),('exclusion_kind', models.CharField(max_length=20)),('condition_1', models.CharField(max_length=200)),('condition_2', models.CharField(blank=True, default='', max_length=200)),('condition_3', models.CharField(blank=True, default='', max_length=200)),('type_name', models.CharField(blank=True, default='', max_length=100)),('is_active', models.BooleanField(default=True)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True))], options={'db_table':'wip_ref_exclusion_type_rule'}),
        migrations.CreateModel(name='WipRefHotLotRule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('sort_no', models.IntegerField(default=0)),('grade', models.CharField(blank=True, default='', max_length=20)),('condition_1', models.CharField(max_length=200)),('condition_2', models.CharField(blank=True, default='', max_length=200)),('condition_3', models.CharField(blank=True, default='', max_length=200)),('type_name', models.CharField(blank=True, default='', max_length=100)),('is_active', models.BooleanField(default=True)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True))], options={'db_table':'wip_ref_hot_lot_rule'}),
    ]
